version: '3.9'

services: 
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:
      - 3008:8000
    volumes:
      - ./api:/var/www/laravel-api-app
    environment:
      TZ: Asia/Tokyo
    depends_on: 
      - db
    links:
      - db
    stdin_open: true
    tty: true

  nginx:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - ./api:/var/www/laravel-api-app
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  
  db:
    image: mysql:8.0
    environment: 
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '33066:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
